configfile: "config/config.yaml"

IDX = config['subcube_id']

include: "rules/chunk_data.smk"
include: "rules/run_sofia.smk"
include: "rules/concatenate_catalogs.smk"
include: "rules/visualize_products.smk"


rule final_catalog:
    input:
        "results/plots/plot1.png",
        "results/final_catalog.csv"

