configfile: "config/config.yaml"

IDX = config['subcube_id']

include: "rules/chunk_data.smk"
include: "rules/run_sofia.smk"
include: "rules/concatenate_catalogs.smk"
include: "rules/visualize_products.smk"
include: "rules/summary.smk"


rule all:
    input:
        "results/catalogs/final_catalog.csv",
        "results/plots/output_params_distribution.png",
        "summary/dag.svg",
        "summary/rulegraph.svg"
