name: snakemake
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - gitpython=3.1.18
  - ipython=7.25.0
  - jinja2=3.0.1
  - jupyterlab=3.0.16
  - jupyterlab_pygments=0.1.2
  - networkx=2.6.1
  - pygments=2.9.0
  - pygraphviz=1.7
  - pytest=6.2.4
  - python=3.9.6
  - python-wget=3.2
  - snakemake-minimal=6.5.3
