site_name: HI-FRIENDS SDC2
site_description: 'Documentation to describe the solution by HI-FRIENDS to the SDC2'
site_author: 'Laura Darriba'
repo_url: 

nav:
    - Home: index.md
    - Methodology: methodology.md
    - Workflow: workflow.md
    - Workflow installation: installation.md
    - Execution: execution.md
    - Documentation for developers: developers.md
    - SDC2 HI-FRIENDS participation: results.md
    - SDC2 reproducibility award: reproducibility.md
    - Acknowledgements: acknowledgements.md 


theme:
    name: readthedocs
    highlightjs: true

markdown_extensions:
  - toc:
      permalink: True
  - admonition

extra_javascript:
  - 'javascripts/extra.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
